#!/bin/bash

if [[ "$#" > 0 ]]; then
  GANDALF="$1"; shift
fi

if [[ -z "${GANDALF:-}" ]]; then
  GANDALF="$(pwd -P)"
fi

export GANDALF

if [[ ! -x "$(type -P gpg 2>&-)" ]]; then
  echo "ERROR: could not find gpg tool" 1>&2
  false
fi
