#!/bin/bash

#/ NAME
#/     edit bundle -- edit a password bundle
#/
#/ SYNOPSIS
#/     edit bundle name

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require gandalf "${GANDALF:-$shome}"
require gandalf_

readonly cfg_gandalf="$GANDALF/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    local default_bundle="$(ryaml $cfg_gandalf bundle default)"
    if [[ -n "$default_bundle" ]]; then
      set -- "$default_bundle" "$@"
    fi
  fi

  if [[ "$#" = 0 ]]; then
    logger_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift
  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"

  set +f
  gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/gpg/"*
  set -f

  readonly local tmp_container="$(mktemp -d -t XXXXXXXXX)"
  readonly local tmp_buffer="$(TMPDIR="$tmp_container" mktemp -t XXXXXXXXX)"

  gpg -a -d "$(secrets_path)/${nm_bundle}.yml.gpg" > "$tmp_buffer"
  "${EDITOR:-vim}" "$tmp_buffer"

  readonly local tmp_bundle="$(mktemp -t XXXXXXXXX)"
  if gpg --yes --trust-model always --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$tmp_bundle" $(recipients) "$tmp_buffer"; then
    mv -f "$tmp_bundle" "$(secrets_path)/$nm_bundle.yml.gpg"
  else
    rm -f "$tmp_bundle"
  fi

  rm -f "$tmp_keyring" "$tmp_buffer"
  rmdir "$tmp_container"
}

require sub "$BASH_SOURCE" "$@"
