#!/bin/bash

#/ NAME
#/     edit passwords -- edit a password bundle
#/
#/ SYNOPSIS
#/     edit passwords bundle

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

readonly cfg_gandalf="$shome/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    log_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift
  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"

  set +f
  gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/gpg/"*
  set -f

  readonly local tmp_container="$(mktemp -d -t XXXXXXXXX)"
  readonly local tmp_buffer="$(TMPDIR="$tmp_container" mktemp -t XXXXXXXXX)"

  gpg -a -d "$(secrets_path)/${nm_bundle}.yml.gpg" > "$tmp_buffer"
  "${EDITOR:-vim}" "$tmp_buffer"

  readonly local tmp_bundle="$(mktemp -t XXXXXXXXX)"
  if gpg --yes --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$tmp_bundle" $(recipients) "$tmp_buffer"; then
    mv -f "$tmp_bundle" "$(secrets_path)/$nm_bundle.yml.gpg"
  else
    rm -f "$tmp_bundle"
  fi

  rm -f "$tmp_keyring" "$tmp_buffer"
  rmdir "$tmp_container"
}

function keys {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" keys | awk '$1 == "-" { print $NF }' | xargs --
}

function keys_path {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" keys_path
}

function secrets_path {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" secrets_path
}

function recipients {
  local _a
  for _a in $(keys); do
    echo -n "-r $_a"
  done
}

require sub "$BASH_SOURCE" "$@"
