#!/bin/bash

#/ NAME
#/     list bundle -- list the bundle for a bundle
#/
#/ SYNOPSIS
#/     list bundle name

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require gandalf "${GANDALF:-$shome}"
require gandalf_

readonly cfg_gandalf="$GANDALF/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    local default_bundle="$(ryaml $cfg_gandalf bundle default)"
    if [[ -n "$default_bundle" ]]; then
      set -- "$default_bundle" "$@"
    fi
  fi

  if [[ "$#" = 0 ]]; then
    logger_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift

  gpg -a -d "$(secrets_path)/${nm_bundle}.yml.gpg"
}

require sub "$BASH_SOURCE" "$@"
