#!/bin/bash

#/ NAME
#/     list passwords -- list the passwords for a bundle
#/
#/ SYNOPSIS
#/     list passwords [bundle]
#/       the default bundle name is secrets

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

DEFINE_string "secrets" "secrets" "Name of secrets bundle in secrets/" "s"

# entry point
function main {
  gpg -d "$shome/secrets/$FLAGS_secrets.yml.gpg"
}

require sub "$BASH_SOURCE" "$@"
