#!/bin/bash

#/ NAME
#/     list bundle -- list the bundle for a bundle
#/
#/ SYNOPSIS
#/     list bundle name

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

readonly cfg_gandalf="$shome/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    log_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift

  gpg -a -d "$(secrets_path)/${nm_bundle}.yml.gpg"
}

function secrets_path {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" secrets_path
}

require sub "$BASH_SOURCE" "$@"
