#!/bin/bash

#/ NAME
#/     new passwords -- create a new password bundle
#/
#/ SYNOPSIS
#/     new passwords bundle

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

readonly cfg_gandalf="$shome/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    logger_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift
  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"

  local _rcpt
  for _rcpt in $(keys); do
    gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/gpg/$_rcpt"
  done

  echo "---" | gpg --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$(secrets_path)/$nm_bundle.yml.gpg" $(recipients)

  rm -f "$tmp_keyring"
}

function keys {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" keys | awk '$1 == "-" { print $NF }' | xargs --
}

function keys_path {
  ryaml "$cfg_gandalf" keys_path
}

function secrets_path {
  ryaml "$cfg_gandalf" bundle "$nm_bundle" secrets_path
}

function recipients {
  local _a
  for _a in $(keys); do
    echo -n "-r $_a"
  done
}

require sub "$BASH_SOURCE" "$@"
