#!/bin/bash

#/ NAME
#/     new bundle -- create a new password bundle
#/
#/ SYNOPSIS
#/     new bundle name

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _gandalf "${GANDALF:-$shome}"
require _gandalf_

readonly cfg_gandalf="$GANDALF/config/gandalf.yml"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    logger_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift
  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"

  local _rcpt
  for _rcpt in $(keys); do
    gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/gpg/$_rcpt"
  done

  echo "---" | gpg --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$(secrets_path)/$nm_bundle.gpg" $(recipients)

  rm -f "$tmp_keyring"
}

require sub "$BASH_SOURCE" "$@"
